#ifndef DIRECTION_H
#define DIRECTION_H

typedef enum DIRECTION {
    DIRECTION_UP,
    DIRECTION_DOWN,
    DIRECTION_LEFT,
    DIRECTION_RIGHT,
    DIRECTION_NONE
} DIRECTION;


#endif // DIRECTION_H