#! /bin/sh

mkdir build
rm -rfd build/**
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../src
cmake --build . --target SnakeGame --clean-first -- -j $(nproc)
cd ..
rm -rfd build/**
ln -sf bin/Release/SnakeGame SnakeGame
